pipeline {
    agent any

    environment {
        GIT_REPO = "https://github.com/Benihaut/vo.git"
        GIT_BRANCH = "main"
        DEPLOY_DIR = "web003"
        PROJECT_SUBFOLDER = "projetcda"
        UPLOAD_DIR = "/var/www/html/${DEPLOY_DIR}/public/uploads/articles"
    }

    stages {
        stage('Cloner le dépôt') {
            steps {
                sh "rm -rf ${DEPLOY_DIR}"
                sh "git clone -b ${GIT_BRANCH} ${GIT_REPO} ${DEPLOY_DIR}"
            }
        }

        stage('Installation des dépendances') {
            steps {
                dir("${DEPLOY_DIR}/${PROJECT_SUBFOLDER}") {
                    sh 'composer install --optimize-autoloader'
                }
            }
        }

        stage('Configuration de l\'environnement') {
            steps {
                script {
                    def envLocal = """
                    APP_ENV=prod
                    APP_DEBUG=1
                    DATABASE_URL=mysql://root:routitop@127.0.0.1:3306/${DEPLOY_DIR}?serverVersion=8.3.0&charset=utf8mb4
                    """
                    writeFile file: "${DEPLOY_DIR}/${PROJECT_SUBFOLDER}/.env.local", text: envLocal
                }
            }
        }

        stage('Migration de la base de données') {
            steps {
                dir("${DEPLOY_DIR}/${PROJECT_SUBFOLDER}") {
                    sh 'php bin/console doctrine:database:create --if-not-exists --env=prod'
                    sh 'php bin/console doctrine:migrations:migrate --no-interaction --env=prod'
                }
            }
        }

        stage('Nettoyage du cache') {
            steps {
                dir("${DEPLOY_DIR}/${PROJECT_SUBFOLDER}") {
                    sh 'php bin/console cache:clear --env=prod'
                    sh 'php bin/console cache:warmup'
                }
            }
        }

        stage('Déploiement') {
            steps {
                sh "rm -rf /var/www/html/${DEPLOY_DIR}"
                sh "mkdir -p /var/www/html/${DEPLOY_DIR}"
                sh "cp -rT ${DEPLOY_DIR}/${PROJECT_SUBFOLDER} /var/www/html/${DEPLOY_DIR}"
                sh "chmod -R 775 /var/www/html/${DEPLOY_DIR}/var"
                
                // Création et configuration du dossier d'upload
                sh "mkdir -p ${UPLOAD_DIR}"
                sh "chmod -R 775 ${UPLOAD_DIR}"
                sh "chown -R www-data:www-data ${UPLOAD_DIR}"
                
                // Vérification de la création du dossier
                sh "ls -l ${UPLOAD_DIR}"
            }
        }

        stage('Vérification des permissions') {
            steps {
                sh "ls -l ${UPLOAD_DIR}"
                sh "id www-data"
                sh "groups www-data"
            }
        }
    }

    post {
        success {
            echo 'Déploiement réussi !'
        }
        failure {
            echo 'Erreur lors du déploiement.'
        }
    }
}

